In [1]:
import pickle

with open("movies.p", "rb") as f:
    data = pickle.load(f)

print(type(data))  # could be dict, list, DataFrame, etc.

<class 'pandas.core.frame.DataFrame'>

In [2]:
import pandas as pd

# Load DataFrame from pickle file
wards = pd.read_pickle("ward.p")
census = pd.read_pickle('census.p')
print(wards.head())
print(census.head())

  ward            alderman                          address    zip
0    1  Proco "Joe" Moreno        2058 NORTH WESTERN AVENUE  60647
1    2       Brian Hopkins       1400 NORTH  ASHLAND AVENUE  60622
2    3          Pat Dowell          5046 SOUTH STATE STREET  60609
3    4    William D. Burns  435 EAST 35TH STREET, 1ST FLOOR  60616
4    5  Leslie A. Hairston            2325 EAST 71ST STREET  60649
  ward  pop_2000  pop_2010 change                                  address  \
0    1     52951     56149     6%              2765 WEST SAINT MARY STREET
1    2     54361     55805     3%                 WM WASTE MANAGEMENT 1500
2    3     40385     53039    31%                      17 EAST 38TH STREET
3    4     51953     54589     5%  31ST ST HARBOR BUILDING LAKEFRONT TRAIL
4    5     55302     51455    -7%  JACKSON PARK LAGOON SOUTH CORNELL DRIVE

     zip
0  60647
1  60622
2  60653
3  60653
4  60637

# Inner join

In [3]:
inner_join_wards_census = wards.merge(census, on='ward')
inner_join_wards_census

,ward,alderman,address_x,zip_x,pop_2000,pop_2010,change,address_y,zip_y
0,1,"Proco ""Joe"" Moreno",2058 NORTH WESTERN AVENUE,60647,52951,56149,6%,2765 WEST SAINT MARY STREET,60647
1,2,Brian Hopkins,1400 NORTH ASHLAND AVENUE,60622,54361,55805,3%,WM WASTE MANAGEMENT 1500,60622
2,3,Pat Dowell,5046 SOUTH STATE STREET,60609,40385,53039,31%,17 EAST 38TH STREET,60653
3,4,William D. Burns,"435 EAST 35TH STREET, 1ST FLOOR",60616,51953,54589,5%,31ST ST HARBOR BUILDING LAKEFRONT TRAIL,60653
4,5,Leslie A. Hairston,2325 EAST 71ST STREET,60649,55302,51455,-7%,JACKSON PARK LAGOON SOUTH CORNELL DRIVE,60637
5,6,Roderick T. Sawyer,8001 S. MARTIN LUTHER KING DRIVE,60619,54989,52341,-5%,150 WEST 74TH STREET,60636
6,7,Gregory I. Mitchell,2249 EAST 95TH STREET,60617,54593,51581,-6%,8549 SOUTH OGLESBY AVENUE,60617
7,8,Michelle A. Harris,8539 SOUTH COTTAGE GROVE AVENUE,60619,54039,51687,-4%,1346-1352 EAST 75TH STREET,60649
8,9,Anthony A. Beale,34 EAST 112TH PLACE,60628,52008,51519,-1%,11039-11059 SOUTH WENTWORTH AVENUE,60628
9,10,Susan Sadlowski Garza,10500 SOUTH EWING AVENUE,60617,56613,51535,-9%,10534 SOUTH AVENUE F,46394
10,11,Patrick Daley Thompson,3659 SOUTH HALSTED STREET,60609,64228,51497,-20%,943-947 WEST 14TH PLACE,60607
11,12,George Cardenas,3476 SOUTH ARCHER AVENUE,60608,68922,52235,-24%,CP 46 STEVENSON EXPRESSWAY,60632
12,13,Marty Quinn,6500 SOUTH PULASKI ROAD,60629,64382,53722,-17%,SOUTH RAMP SOUTH LARAMIE AVENUE,60638
13,14,Edward M. Burke,2650 WEST 51ST STREET,60632,80143,54031,-33%,4540 WEST 51ST STREET,60632
14,15,Raymond A. Lopez,1650 WEST 63RD STREET,60636,56057,51501,-8%,CHICAGO FIRE DEPARTMENT ENGINE COMPANY 123 2215,60632
15,16,Toni L. Foulkes,3045 WEST 63RD STREET,60629,50205,51954,3%,6036 SOUTH WOOD STREET,60636
16,17,David H. Moore,7313 SOUTH ASHLAND AVENUE,60636,49264,51846,5%,7216 SOUTH WINCHESTER AVENUE,60636
17,18,Derrick G. Curtis,8359 SOUTH PULASKI ROAD,60652,55043,52992,-4%,3286 WEST COLUMBUS AVENUE,60652
18,19,Matthew J. O'Shea,10400 SOUTH WESTERN AVENUE,60643,54546,51525,-6%,9999 SOUTH FRANCISCO AVENUE,60805
19,20,Willie B. Cochran,6357 SOUTH COTTAGE GROVE AVENUE,60637,51854,52372,1%,DAN RYAN EXPRESSWAY PARK MANOR,60621
20,21,"Howard B. Brookins, Jr.","9011 SOUTH ASHLAND AVENUE, UNIT B",60620,51751,51632,0%,8852-8854 SOUTH EMERALD AVENUE,60620
21,22,Ricardo Munoz,2500 SOUTH ST. LOUIS AVENUE,60623,59734,53515,-10%,4233 WEST 36TH STREET,60632
22,23,Michael R. Zalewski,6247 SOUTH ARCHER AVENUE,60638,63691,53728,-16%,CHICAGO MIDWAY INTERNATIONAL AIRPORT WEST 62ND...,60629
23,24,"Michael Scott, Jr.",1158 SOUTH KEELER AVENUE,60624,50879,54909,8%,1635 SOUTH CHRISTIANA AVENUE,60623
24,25,"Daniel ""Danny"" Solis",1800 SOUTH BLUE ISLAND AVENUE,60608,55954,54539,-3%,1632-1746 SOUTH MILLER STREET,60608
25,26,Roberto Maldonado,2511 WEST DIVISION STREET,60622,56841,53516,-6%,LITTLE CUBS FIELD COMFORT STATION 1400,60622
26,27,"Walter Burnett, Jr.",4 NORTH WESTERN AVENUE,60612,61287,52939,-14%,2151-2153 WEST CHICAGO AVENUE,60651
27,28,Jason C. Ervin,2602 WEST 16TH STREET,60612,49423,55199,12%,RML SPECIALTY HOSPITAL 3435,60624
28,29,Chris Taliaferro,6272 WEST NORTH AVENUE,60639,61949,55267,-11%,1241 NORTH RIDGELAND AVENUE,60302
29,30,Ariel E. Reyboras,3559 NORTH MILWAUKEE AVENUE,60641,72698,55560,-24%,5118 WEST FLETCHER STREET,60641
30,31,"Milagros ""Milly"" Santiago",2521 NORTH PULASKI ROAD,60639,65045,53724,-17%,2854 NORTH KEATING AVENUE,60641
31,32,Scott Waguespack,2657 NORTH CLYBOURN AVENUE,60614,57204,55184,-4%,2901 NORTH WASHTENAW AVENUE,60618
32,33,Deborah Mell,3001 WEST IRVING PARK ROAD,60618,63695,55598,-13%,4041-4043 NORTH RICHMOND STREET,60625
33,34,Carrie M. Austin,507 WEST 111TH STREET,60628,49922,51599,3%,11544-11546 SOUTH PEORIA STREET,60827
34,35,Carlos Ramirez-Rosa,2710 NORTH SAWYER AVENUE,60647,57588,55281,-4%,3634 WEST BELMONT AVENUE,60618
35,36,Gilbert Villegas,6934 WEST DIVERSEY,60607,63376,54766,-14%,2918 NORTH RUTHERFORD AVENUE,60634
36,37,Emma M. Mitts,4924 WEST CHICAGO AVENUE,60651,56120,51538,-8%,4738-4748 WEST RICE STREET,60651
37,38,Nicholas Sposato,3821 NORTH HARLEM AVENUE,60634,66011,56001,-15%,7307-7331 WEST IRVING PARK ROAD,60706
38,39,Margaret Laurino,4404 WEST LAWRENCE AVENUE,60630,64291,55882,-13%,QUEEN OF ALL SAINTS BASILICA 6280,60646
39,40,Patrick J. O'Connor,5850 NORTH LINCOLN AVENUE,60659,58652,55319,-6%,5536 NORTH ARTESIAN AVENUE,60645
40,41,Anthony V. Napolitano,7442 NORTH HARLEM AVENUE,60631,56127,55991,0%,1652 SOUTH CLIFTON AVENUE,60068
41,42,Brendan Reilly,"325 WEST HURON STREET, SUITE 510",60654,68102,55870,-18%,410-420 WEST GRAND AVENUE,60654
42,43,Michelle Smith,2523 NORTH HALSTED STREET,60614,57668,56170,-3%,LINCOLN PARK ZOO 2001,60614
43,44,Tom Tunney,3223 NORTH SHEFFIELD AVENUE,60657,58758,56058,-5%,507-513 WEST ALDINE AVENUE,60657
44,45,John S. Arena,4754 NORTH MILWAUKEE AVENUE,60630,60653,55967,-8%,CONGREGATIONAL CHURCH OF JEFFERSON PARK 5320,60630
45,46,James Cappleman,4544 NORTH BROADWAY AVENUE,60640,56587,53784,-5%,UPTOWN BROADWAY BUILDING 4743-4763,60640
46,47,Ameya Pawar,4243 NORTH LINCOLN AVENUE,60618,52108,55074,6%,2153 WEST BERTEAU AVENUE,60618
47,48,Harry Osterman,5533 NORTH BROADWAY AVENUE,60640,56246,55014,-2%,1025 WEST HOLLYWOOD AVENUE,60660
48,49,Joe Moore,7356 NORTH GREENVIEW AVENUE,60626,59435,54633,-8%,1426 WEST ESTES AVENUE,60645
49,50,Debra L. Silverstein,"2949 WEST DEVON AVENUE, SUITE A",60659,62383,55809,-11%,2638 WEST NORTH SHORE AVENUE,60645

In [4]:
inner_join_wards_census = wards.merge(census, on='ward', suffixes=['_ward', '_cens'])
inner_join_wards_census

,ward,alderman,address_ward,zip_ward,pop_2000,pop_2010,change,address_cens,zip_cens
0,1,"Proco ""Joe"" Moreno",2058 NORTH WESTERN AVENUE,60647,52951,56149,6%,2765 WEST SAINT MARY STREET,60647
1,2,Brian Hopkins,1400 NORTH ASHLAND AVENUE,60622,54361,55805,3%,WM WASTE MANAGEMENT 1500,60622
2,3,Pat Dowell,5046 SOUTH STATE STREET,60609,40385,53039,31%,17 EAST 38TH STREET,60653
3,4,William D. Burns,"435 EAST 35TH STREET, 1ST FLOOR",60616,51953,54589,5%,31ST ST HARBOR BUILDING LAKEFRONT TRAIL,60653
4,5,Leslie A. Hairston,2325 EAST 71ST STREET,60649,55302,51455,-7%,JACKSON PARK LAGOON SOUTH CORNELL DRIVE,60637
5,6,Roderick T. Sawyer,8001 S. MARTIN LUTHER KING DRIVE,60619,54989,52341,-5%,150 WEST 74TH STREET,60636
6,7,Gregory I. Mitchell,2249 EAST 95TH STREET,60617,54593,51581,-6%,8549 SOUTH OGLESBY AVENUE,60617
7,8,Michelle A. Harris,8539 SOUTH COTTAGE GROVE AVENUE,60619,54039,51687,-4%,1346-1352 EAST 75TH STREET,60649
8,9,Anthony A. Beale,34 EAST 112TH PLACE,60628,52008,51519,-1%,11039-11059 SOUTH WENTWORTH AVENUE,60628
9,10,Susan Sadlowski Garza,10500 SOUTH EWING AVENUE,60617,56613,51535,-9%,10534 SOUTH AVENUE F,46394
10,11,Patrick Daley Thompson,3659 SOUTH HALSTED STREET,60609,64228,51497,-20%,943-947 WEST 14TH PLACE,60607
11,12,George Cardenas,3476 SOUTH ARCHER AVENUE,60608,68922,52235,-24%,CP 46 STEVENSON EXPRESSWAY,60632
12,13,Marty Quinn,6500 SOUTH PULASKI ROAD,60629,64382,53722,-17%,SOUTH RAMP SOUTH LARAMIE AVENUE,60638
13,14,Edward M. Burke,2650 WEST 51ST STREET,60632,80143,54031,-33%,4540 WEST 51ST STREET,60632
14,15,Raymond A. Lopez,1650 WEST 63RD STREET,60636,56057,51501,-8%,CHICAGO FIRE DEPARTMENT ENGINE COMPANY 123 2215,60632
15,16,Toni L. Foulkes,3045 WEST 63RD STREET,60629,50205,51954,3%,6036 SOUTH WOOD STREET,60636
16,17,David H. Moore,7313 SOUTH ASHLAND AVENUE,60636,49264,51846,5%,7216 SOUTH WINCHESTER AVENUE,60636
17,18,Derrick G. Curtis,8359 SOUTH PULASKI ROAD,60652,55043,52992,-4%,3286 WEST COLUMBUS AVENUE,60652
18,19,Matthew J. O'Shea,10400 SOUTH WESTERN AVENUE,60643,54546,51525,-6%,9999 SOUTH FRANCISCO AVENUE,60805
19,20,Willie B. Cochran,6357 SOUTH COTTAGE GROVE AVENUE,60637,51854,52372,1%,DAN RYAN EXPRESSWAY PARK MANOR,60621
20,21,"Howard B. Brookins, Jr.","9011 SOUTH ASHLAND AVENUE, UNIT B",60620,51751,51632,0%,8852-8854 SOUTH EMERALD AVENUE,60620
21,22,Ricardo Munoz,2500 SOUTH ST. LOUIS AVENUE,60623,59734,53515,-10%,4233 WEST 36TH STREET,60632
22,23,Michael R. Zalewski,6247 SOUTH ARCHER AVENUE,60638,63691,53728,-16%,CHICAGO MIDWAY INTERNATIONAL AIRPORT WEST 62ND...,60629
23,24,"Michael Scott, Jr.",1158 SOUTH KEELER AVENUE,60624,50879,54909,8%,1635 SOUTH CHRISTIANA AVENUE,60623
24,25,"Daniel ""Danny"" Solis",1800 SOUTH BLUE ISLAND AVENUE,60608,55954,54539,-3%,1632-1746 SOUTH MILLER STREET,60608
25,26,Roberto Maldonado,2511 WEST DIVISION STREET,60622,56841,53516,-6%,LITTLE CUBS FIELD COMFORT STATION 1400,60622
26,27,"Walter Burnett, Jr.",4 NORTH WESTERN AVENUE,60612,61287,52939,-14%,2151-2153 WEST CHICAGO AVENUE,60651
27,28,Jason C. Ervin,2602 WEST 16TH STREET,60612,49423,55199,12%,RML SPECIALTY HOSPITAL 3435,60624
28,29,Chris Taliaferro,6272 WEST NORTH AVENUE,60639,61949,55267,-11%,1241 NORTH RIDGELAND AVENUE,60302
29,30,Ariel E. Reyboras,3559 NORTH MILWAUKEE AVENUE,60641,72698,55560,-24%,5118 WEST FLETCHER STREET,60641
30,31,"Milagros ""Milly"" Santiago",2521 NORTH PULASKI ROAD,60639,65045,53724,-17%,2854 NORTH KEATING AVENUE,60641
31,32,Scott Waguespack,2657 NORTH CLYBOURN AVENUE,60614,57204,55184,-4%,2901 NORTH WASHTENAW AVENUE,60618
32,33,Deborah Mell,3001 WEST IRVING PARK ROAD,60618,63695,55598,-13%,4041-4043 NORTH RICHMOND STREET,60625
33,34,Carrie M. Austin,507 WEST 111TH STREET,60628,49922,51599,3%,11544-11546 SOUTH PEORIA STREET,60827
34,35,Carlos Ramirez-Rosa,2710 NORTH SAWYER AVENUE,60647,57588,55281,-4%,3634 WEST BELMONT AVENUE,60618
35,36,Gilbert Villegas,6934 WEST DIVERSEY,60607,63376,54766,-14%,2918 NORTH RUTHERFORD AVENUE,60634
36,37,Emma M. Mitts,4924 WEST CHICAGO AVENUE,60651,56120,51538,-8%,4738-4748 WEST RICE STREET,60651
37,38,Nicholas Sposato,3821 NORTH HARLEM AVENUE,60634,66011,56001,-15%,7307-7331 WEST IRVING PARK ROAD,60706
38,39,Margaret Laurino,4404 WEST LAWRENCE AVENUE,60630,64291,55882,-13%,QUEEN OF ALL SAINTS BASILICA 6280,60646
39,40,Patrick J. O'Connor,5850 NORTH LINCOLN AVENUE,60659,58652,55319,-6%,5536 NORTH ARTESIAN AVENUE,60645
40,41,Anthony V. Napolitano,7442 NORTH HARLEM AVENUE,60631,56127,55991,0%,1652 SOUTH CLIFTON AVENUE,60068
41,42,Brendan Reilly,"325 WEST HURON STREET, SUITE 510",60654,68102,55870,-18%,410-420 WEST GRAND AVENUE,60654
42,43,Michelle Smith,2523 NORTH HALSTED STREET,60614,57668,56170,-3%,LINCOLN PARK ZOO 2001,60614
43,44,Tom Tunney,3223 NORTH SHEFFIELD AVENUE,60657,58758,56058,-5%,507-513 WEST ALDINE AVENUE,60657
44,45,John S. Arena,4754 NORTH MILWAUKEE AVENUE,60630,60653,55967,-8%,CONGREGATIONAL CHURCH OF JEFFERSON PARK 5320,60630
45,46,James Cappleman,4544 NORTH BROADWAY AVENUE,60640,56587,53784,-5%,UPTOWN BROADWAY BUILDING 4743-4763,60640
46,47,Ameya Pawar,4243 NORTH LINCOLN AVENUE,60618,52108,55074,6%,2153 WEST BERTEAU AVENUE,60618
47,48,Harry Osterman,5533 NORTH BROADWAY AVENUE,60640,56246,55014,-2%,1025 WEST HOLLYWOOD AVENUE,60660
48,49,Joe Moore,7356 NORTH GREENVIEW AVENUE,60626,59435,54633,-8%,1426 WEST ESTES AVENUE,60645
49,50,Debra L. Silverstein,"2949 WEST DEVON AVENUE, SUITE A",60659,62383,55809,-11%,2638 WEST NORTH SHORE AVENUE,60645

# one-to-one relationship

In [5]:
license = pd.read_pickle('licenses.p')
print(license.shape)
print(license.head())

(10000, 6)
  account ward  aid                   business               address    zip
0  307071    3  743       REGGIE'S BAR & GRILL       2105 S STATE ST  60616
1      10   10  829                 HONEYBEERS   13200 S HOUSTON AVE  60633
2   10002   14  775                CELINA DELI     5089 S ARCHER AVE  60632
3   10005   12  NaN  KRAFT FOODS NORTH AMERICA        2005 W 43RD ST  60609
4   10044   44  638  NEYBOUR'S TAVERN & GRILLE  3651 N SOUTHPORT AVE  60613

In [6]:
ward_license = wards.merge(license, on='ward', suffixes=['_ward', '_lis'])
ward_license

,ward,alderman,address_ward,zip_ward,account,aid,business,address_lis,zip_lis
0,1,"Proco ""Joe"" Moreno",2058 NORTH WESTERN AVENUE,60647,12024,NaN,DIGILOG ELECTRONICS,1038 N ASHLAND AVE,60622
1,1,"Proco ""Joe"" Moreno",2058 NORTH WESTERN AVENUE,60647,14446,743,EMPTY BOTTLE INC,1035 N WESTERN AVE 1ST,60622
2,1,"Proco ""Joe"" Moreno",2058 NORTH WESTERN AVENUE,60647,14624,775,LITTLE MEL'S HOT DOG,2205 N CALIFORNIA AVE,60647
3,1,"Proco ""Joe"" Moreno",2058 NORTH WESTERN AVENUE,60647,14987,NaN,MR. BROWN'S LOUNGE,2301 W CHICAGO AVE 1ST,60622
4,1,"Proco ""Joe"" Moreno",2058 NORTH WESTERN AVENUE,60647,15642,814,Beat Kitchen,2000-2100 W DIVISION ST,60622
...,...,...,...,...,...,...,...,...,...
9995,50,Debra L. Silverstein,"2949 WEST DEVON AVENUE, SUITE A",60659,6604,829,SIBLINGS,2827 W HOWARD ST,60645
9996,50,Debra L. Silverstein,"2949 WEST DEVON AVENUE, SUITE A",60659,66512,NaN,CHANDNI BOUTIQUE INC,2503 W DEVON AVE 2ND,60659
9997,50,Debra L. Silverstein,"2949 WEST DEVON AVENUE, SUITE A",60659,66638,NaN,PIDC PAN HOUSE,6342 N WESTERN AVE 1ST,60659
9998,50,Debra L. Silverstein,"2949 WEST DEVON AVENUE, SUITE A",60659,80484,NaN,WHEEL OF CHICAGO,6229 N WESTERN AVE,60659
9999,50,Debra L. Silverstein,"2949 WEST DEVON AVENUE, SUITE A",60659,81088,763,BISMILLAH ZABIHA MEAT & GROCER,2742 W DEVON AVE # STREE,60659

In [7]:
print(wards.shape)
print(ward_license.shape)

(50, 4)
(10000, 9)

# Merge multiple tables

In [8]:
wards

   ward                   alderman                            address    zip
0     1         Proco "Joe" Moreno          2058 NORTH WESTERN AVENUE  60647
1     2              Brian Hopkins         1400 NORTH  ASHLAND AVENUE  60622
2     3                 Pat Dowell            5046 SOUTH STATE STREET  60609
3     4           William D. Burns    435 EAST 35TH STREET, 1ST FLOOR  60616
4     5         Leslie A. Hairston              2325 EAST 71ST STREET  60649
5     6         Roderick T. Sawyer   8001 S. MARTIN LUTHER KING DRIVE  60619
6     7        Gregory I. Mitchell              2249 EAST 95TH STREET  60617
7     8         Michelle A. Harris    8539 SOUTH COTTAGE GROVE AVENUE  60619
8     9           Anthony A. Beale                34 EAST 112TH PLACE  60628
9    10      Susan Sadlowski Garza           10500 SOUTH EWING AVENUE  60617
10   11     Patrick Daley Thompson          3659 SOUTH HALSTED STREET  60609
11   12            George Cardenas           3476 SOUTH ARCHER AVENUE  60608
12   13                Marty Quinn            6500 SOUTH PULASKI ROAD  60629
13   14            Edward M. Burke              2650 WEST 51ST STREET  60632
14   15           Raymond A. Lopez              1650 WEST 63RD STREET  60636
15   16            Toni L. Foulkes              3045 WEST 63RD STREET  60629
16   17             David H. Moore          7313 SOUTH ASHLAND AVENUE  60636
17   18          Derrick G. Curtis            8359 SOUTH PULASKI ROAD  60652
18   19          Matthew J. O'Shea         10400 SOUTH WESTERN AVENUE  60643
19   20          Willie B. Cochran    6357 SOUTH COTTAGE GROVE AVENUE  60637
20   21    Howard B. Brookins, Jr.  9011 SOUTH ASHLAND AVENUE, UNIT B  60620
21   22              Ricardo Munoz        2500 SOUTH ST. LOUIS AVENUE  60623
22   23        Michael R. Zalewski           6247 SOUTH ARCHER AVENUE  60638
23   24         Michael Scott, Jr.           1158 SOUTH KEELER AVENUE  60624
24   25       Daniel "Danny" Solis      1800 SOUTH BLUE ISLAND AVENUE  60608
25   26          Roberto Maldonado          2511 WEST DIVISION STREET  60622
26   27        Walter Burnett, Jr.             4 NORTH WESTERN AVENUE  60612
27   28             Jason C. Ervin              2602 WEST 16TH STREET  60612
28   29           Chris Taliaferro             6272 WEST NORTH AVENUE  60639
29   30          Ariel E. Reyboras        3559 NORTH MILWAUKEE AVENUE  60641
30   31  Milagros "Milly" Santiago            2521 NORTH PULASKI ROAD  60639
31   32           Scott Waguespack         2657 NORTH CLYBOURN AVENUE  60614
32   33               Deborah Mell         3001 WEST IRVING PARK ROAD  60618
33   34           Carrie M. Austin              507 WEST 111TH STREET  60628
34   35        Carlos Ramirez-Rosa           2710 NORTH SAWYER AVENUE  60647
35   36           Gilbert Villegas                 6934 WEST DIVERSEY  60607
36   37              Emma M. Mitts           4924 WEST CHICAGO AVENUE  60651
37   38           Nicholas Sposato          3821  NORTH HARLEM AVENUE  60634
38   39           Margaret Laurino          4404 WEST LAWRENCE AVENUE  60630
39   40        Patrick J. O'Connor          5850 NORTH LINCOLN AVENUE  60659
40   41      Anthony V. Napolitano           7442 NORTH HARLEM AVENUE  60631
41   42             Brendan Reilly   325 WEST HURON STREET, SUITE 510  60654
42   43             Michelle Smith          2523 NORTH HALSTED STREET  60614
43   44                 Tom Tunney        3223 NORTH SHEFFIELD AVENUE  60657
44   45              John S. Arena        4754 NORTH MILWAUKEE AVENUE  60630
45   46            James Cappleman         4544 NORTH BROADWAY AVENUE  60640
46   47                Ameya Pawar          4243 NORTH LINCOLN AVENUE  60618
47   48             Harry Osterman         5533 NORTH BROADWAY AVENUE  60640
48   49                  Joe Moore        7356 NORTH GREENVIEW AVENUE  60626
49   50       Debra L. Silverstein    2949 WEST DEVON AVENUE, SUITE A  60659

In [9]:
census

,ward,pop_2000,pop_2010,change,address,zip
0,1,52951,56149,6%,2765 WEST SAINT MARY STREET,60647
1,2,54361,55805,3%,WM WASTE MANAGEMENT 1500,60622
2,3,40385,53039,31%,17 EAST 38TH STREET,60653
3,4,51953,54589,5%,31ST ST HARBOR BUILDING LAKEFRONT TRAIL,60653
4,5,55302,51455,-7%,JACKSON PARK LAGOON SOUTH CORNELL DRIVE,60637
5,6,54989,52341,-5%,150 WEST 74TH STREET,60636
6,7,54593,51581,-6%,8549 SOUTH OGLESBY AVENUE,60617
7,8,54039,51687,-4%,1346-1352 EAST 75TH STREET,60649
8,9,52008,51519,-1%,11039-11059 SOUTH WENTWORTH AVENUE,60628
9,10,56613,51535,-9%,10534 SOUTH AVENUE F,46394
10,11,64228,51497,-20%,943-947 WEST 14TH PLACE,60607
11,12,68922,52235,-24%,CP 46 STEVENSON EXPRESSWAY,60632
12,13,64382,53722,-17%,SOUTH RAMP SOUTH LARAMIE AVENUE,60638
13,14,80143,54031,-33%,4540 WEST 51ST STREET,60632
14,15,56057,51501,-8%,CHICAGO FIRE DEPARTMENT ENGINE COMPANY 123 2215,60632
15,16,50205,51954,3%,6036 SOUTH WOOD STREET,60636
16,17,49264,51846,5%,7216 SOUTH WINCHESTER AVENUE,60636
17,18,55043,52992,-4%,3286 WEST COLUMBUS AVENUE,60652
18,19,54546,51525,-6%,9999 SOUTH FRANCISCO AVENUE,60805
19,20,51854,52372,1%,DAN RYAN EXPRESSWAY PARK MANOR,60621
20,21,51751,51632,0%,8852-8854 SOUTH EMERALD AVENUE,60620
21,22,59734,53515,-10%,4233 WEST 36TH STREET,60632
22,23,63691,53728,-16%,CHICAGO MIDWAY INTERNATIONAL AIRPORT WEST 62ND...,60629
23,24,50879,54909,8%,1635 SOUTH CHRISTIANA AVENUE,60623
24,25,55954,54539,-3%,1632-1746 SOUTH MILLER STREET,60608
25,26,56841,53516,-6%,LITTLE CUBS FIELD COMFORT STATION 1400,60622
26,27,61287,52939,-14%,2151-2153 WEST CHICAGO AVENUE,60651
27,28,49423,55199,12%,RML SPECIALTY HOSPITAL 3435,60624
28,29,61949,55267,-11%,1241 NORTH RIDGELAND AVENUE,60302
29,30,72698,55560,-24%,5118 WEST FLETCHER STREET,60641
30,31,65045,53724,-17%,2854 NORTH KEATING AVENUE,60641
31,32,57204,55184,-4%,2901 NORTH WASHTENAW AVENUE,60618
32,33,63695,55598,-13%,4041-4043 NORTH RICHMOND STREET,60625
33,34,49922,51599,3%,11544-11546 SOUTH PEORIA STREET,60827
34,35,57588,55281,-4%,3634 WEST BELMONT AVENUE,60618
35,36,63376,54766,-14%,2918 NORTH RUTHERFORD AVENUE,60634
36,37,56120,51538,-8%,4738-4748 WEST RICE STREET,60651
37,38,66011,56001,-15%,7307-7331 WEST IRVING PARK ROAD,60706
38,39,64291,55882,-13%,QUEEN OF ALL SAINTS BASILICA 6280,60646
39,40,58652,55319,-6%,5536 NORTH ARTESIAN AVENUE,60645
40,41,56127,55991,0%,1652 SOUTH CLIFTON AVENUE,60068
41,42,68102,55870,-18%,410-420 WEST GRAND AVENUE,60654
42,43,57668,56170,-3%,LINCOLN PARK ZOO 2001,60614
43,44,58758,56058,-5%,507-513 WEST ALDINE AVENUE,60657
44,45,60653,55967,-8%,CONGREGATIONAL CHURCH OF JEFFERSON PARK 5320,60630
45,46,56587,53784,-5%,UPTOWN BROADWAY BUILDING 4743-4763,60640
46,47,52108,55074,6%,2153 WEST BERTEAU AVENUE,60618
47,48,56246,55014,-2%,1025 WEST HOLLYWOOD AVENUE,60660
48,49,59435,54633,-8%,1426 WEST ESTES AVENUE,60645
49,50,62383,55809,-11%,2638 WEST NORTH SHORE AVENUE,60645

In [10]:
license

,account,ward,aid,business,address,zip
0,307071,3,743,REGGIE'S BAR & GRILL,2105 S STATE ST,60616
1,10,10,829,HONEYBEERS,13200 S HOUSTON AVE,60633
2,10002,14,775,CELINA DELI,5089 S ARCHER AVE,60632
3,10005,12,NaN,KRAFT FOODS NORTH AMERICA,2005 W 43RD ST,60609
4,10044,44,638,NEYBOUR'S TAVERN & GRILLE,3651 N SOUTHPORT AVE,60613
...,...,...,...,...,...,...
9995,8634,10,NaN,J M V CORP,2717 E 95TH ST,60617
9996,86350,42,708,AMERICASH LOANS LLC,103 N WELLS ST 1ST,60606
9997,86352,23,775,MC DONALD'S,6720 W ARCHER AVE 1,60638
9998,86355,43,638,VOSGES HAUT-CHOCOLAT,951 W ARMITAGE AVE 1,60614
9999,86373,20,775,ALMUFLIHI FOOD & LIQUOR,5400-5404 S HALSTED ST 1ST,60609

In [11]:
triple_merge = wards.merge(census, on='ward', suffixes=['', '_cens']) \
    .merge(license, on='ward')

print(triple_merge.shape)

(10000, 14)

In [13]:
help(pd.DataFrame.merge)

Help on function merge in module pandas.core.frame:

merge(self, right: 'DataFrame | Series', how: 'MergeHow' = 'inner', on: 'IndexLabel | AnyArrayLike | None' = None, left_on: 'IndexLabel | AnyArrayLike | None' = None, right_on: 'IndexLabel | AnyArrayLike | None' = None, left_index: 'bool' = False, right_index: 'bool' = False, sort: 'bool' = False, suffixes: 'Suffixes' = ('_x', '_y'), copy: 'bool | None' = None, indicator: 'str | bool' = False, validate: 'MergeValidate | None' = None) -> 'DataFrame'
    Merge DataFrame or named Series objects with a database-style join.

    A named Series object is treated as a DataFrame with a single named column.

    The join is done on columns or indexes. If joining columns on
    columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
    on indexes or indexes on a column or columns, the index will be passed on.
    When performing a cross merge, no column specifications to merge on are
    allowed.

    .. warning::

        If both key columns contain rows where the key is a null value, those
        rows will be matched against each other. This is different from usual SQL
        join behaviour and can lead to unexpected results.

    Parameters
    ----------
    right : DataFrame or named Series
        Object to merge with.
    how : {'left', 'right', 'outer', 'inner', 'cross'}, default 'inner'
        Type of merge to be performed.

        * left: use only keys from left frame, similar to a SQL left outer join;
          preserve key order.
        * right: use only keys from right frame, similar to a SQL right outer join;
          preserve key order.
        * outer: use union of keys from both frames, similar to a SQL full outer
          join; sort keys lexicographically.
        * inner: use intersection of keys from both frames, similar to a SQL inner
          join; preserve the order of the left keys.
        * cross: creates the cartesian product from both frames, preserves the order
          of the left keys.
    on : label or list
        Column or index level names to join on. These must be found in both
        DataFrames. If `on` is None and not merging on indexes then this defaults
        to the intersection of the columns in both DataFrames.
    left_on : label or list, or array-like
        Column or index level names to join on in the left DataFrame. Can also
        be an array or list of arrays of the length of the left DataFrame.
        These arrays are treated as if they are columns.
    right_on : label or list, or array-like
        Column or index level names to join on in the right DataFrame. Can also
        be an array or list of arrays of the length of the right DataFrame.
        These arrays are treated as if they are columns.
    left_index : bool, default False
        Use the index from the left DataFrame as the join key(s). If it is a
        MultiIndex, the number of keys in the other DataFrame (either the index
        or a number of columns) must match the number of levels.
    right_index : bool, default False
        Use the index from the right DataFrame as the join key. Same caveats as
        left_index.
    sort : bool, default False
        Sort the join keys lexicographically in the result DataFrame. If False,
        the order of the join keys depends on the join type (how keyword).
    suffixes : list-like, default is ("_x", "_y")
        A length-2 sequence where each element is optionally a string
        indicating the suffix to add to overlapping column names in
        `left` and `right` respectively. Pass a value of `None` instead
        of a string to indicate that the column name from `left` or
        `right` should be left as-is, with no suffix. At least one of the
        values must not be None.
    copy : bool, default True
        If False, avoid copy if possible.

        .. note::
            The `copy` keyword will change behavior in pandas 3.0.
            `Copy-on-Write
            <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
            will be enabled by default, which means that all methods with a
            `copy` keyword will use a lazy copy mechanism to defer the copy and
            ignore the `copy` keyword. The `copy` keyword will be removed in a
            future version of pandas.

            You can already get the future behavior and improvements through
            enabling copy on write ``pd.options.mode.copy_on_write = True``
    indicator : bool or str, default False
        If True, adds a column to the output DataFrame called "_merge" with
        information on the source of each row. The column can be given a different
        name by providing a string argument. The column will have a Categorical
        type with the value of "left_only" for observations whose merge key only
        appears in the left DataFrame, "right_only" for observations
        whose merge key only appears in the right DataFrame, and "both"
        if the observation's merge key is found in both DataFrames.

    validate : str, optional
        If specified, checks if merge is of specified type.

        * "one_to_one" or "1:1": check if merge keys are unique in both
          left and right datasets.
        * "one_to_many" or "1:m": check if merge keys are unique in left
          dataset.
        * "many_to_one" or "m:1": check if merge keys are unique in right
          dataset.
        * "many_to_many" or "m:m": allowed, but does not result in checks.

    Returns
    -------
    DataFrame
        A DataFrame of the two merged objects.

    See Also
    --------
    merge_ordered : Merge with optional filling/interpolation.
    merge_asof : Merge on nearest keys.
    DataFrame.join : Similar method using indices.

    Examples
    --------
    >>> df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
    ...                     'value': [1, 2, 3, 5]})
    >>> df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
    ...                     'value': [5, 6, 7, 8]})
    >>> df1
        lkey value
    0   foo      1
    1   bar      2
    2   baz      3
    3   foo      5
    >>> df2
        rkey value
    0   foo      5
    1   bar      6
    2   baz      7
    3   foo      8

    Merge df1 and df2 on the lkey and rkey columns. The value columns have
    the default suffixes, _x and _y, appended.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey')
      lkey  value_x rkey  value_y
    0  foo        1  foo        5
    1  foo        1  foo        8
    2  bar        2  bar        6
    3  baz        3  baz        7
    4  foo        5  foo        5
    5  foo        5  foo        8

    Merge DataFrames df1 and df2 with specified left and right suffixes
    appended to any overlapping columns.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey',
    ...           suffixes=('_left', '_right'))
      lkey  value_left rkey  value_right
    0  foo           1  foo            5
    1  foo           1  foo            8
    2  bar           2  bar            6
    3  baz           3  baz            7
    4  foo           5  foo            5
    5  foo           5  foo            8

    Merge DataFrames df1 and df2, but raise an exception if the DataFrames have
    any overlapping columns.

    >>> df1.merge(df2, left_on='lkey', right_on='rkey', suffixes=(False, False))
    Traceback (most recent call last):
    ...
    ValueError: columns overlap but no suffix specified:
        Index(['value'], dtype='object')

    >>> df1 = pd.DataFrame({'a': ['foo', 'bar'], 'b': [1, 2]})
    >>> df2 = pd.DataFrame({'a': ['foo', 'baz'], 'c': [3, 4]})
    >>> df1
          a  b
    0   foo  1
    1   bar  2
    >>> df2
          a  c
    0   foo  3
    1   baz  4

    >>> df1.merge(df2, how='inner', on='a')
          a  b  c
    0   foo  1  3

    >>> df1.merge(df2, how='left', on='a')
          a  b  c
    0   foo  1  3.0
    1   bar  2  NaN

    >>> df1 = pd.DataFrame({'left': ['foo', 'bar']})
    >>> df2 = pd.DataFrame({'right': [7, 8]})
    >>> df1
        left
    0   foo
    1   bar
    >>> df2
        right
    0   7
    1   8

    >>> df1.merge(df2, how='cross')
       left  right
    0   foo      7
    1   foo      8
    2   bar      7
    3   bar      8